In [1]:
import torch


In [ ]:

# Create a matrix
matrix = torch.randn(1000, 1000, device='cuda')  # Use the GPU by specifying device='cuda'

# Perform matrix inversion
inverted_matrix = torch.linalg.inv(matrix)

# Print the result
print(inverted_matrix)


In [6]:
E.device

device(type='cpu')

In [9]:
tensor = torch.tensor([1.0])

In [10]:
tensor

tensor([1.])

In [11]:

scalar = tensor.item()

In [12]:
scalar

1.0

In [9]:
E.shape

torch.Size([1])

In [ ]:
E=torch.tensor([1])

In [33]:
from hamiltonians.lead_hamiltonian import Lead
# Example usage
mu_values = [20, -20, 1]
temperature = 300
Ny=10
t_lead_central = 15

# Create lead objects
leads = [Lead(mu, t_lead_central, temperature, Ny,Ny) for mu in mu_values]

# Set positions for leads
leads[0].position = torch.arange(1, Ny + 1)
leads[1].position = leads[0].position + Ny * (Ny - 1)  # Assuming Ny is defined elsewhere
leads[2].position = torch.tensor([3 * Ny + 1])

# Print lead information for debugging
for lead in leads:
    print(lead)

Lead(mu=20, temperature=300, lambda_=0)
Lead(mu=-20, temperature=300, lambda_=0)
Lead(mu=1, temperature=300, lambda_=0)


In [34]:
leads[0].epsilon0

tensor([[ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [10.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0., 10.,  0., 10.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0., 10.,  0., 10.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 10.,  0., 10.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., 10.,  0., 10.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0., 10.,  0., 10.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0., 10.,  0., 10.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0., 10.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  0.]])

In [28]:
from utils.lead_decimation import lead_decimation
from utils.fermi_distribution import fermi_distribution
from time import time
# Define parameters
t = torch.tensor([[20.0, 0.0], [0.0, 20.0]],dtype=torch.complex64,device='cpu' if torch.cuda.is_available() else 'cpu')
epsilon0 = torch.tensor([[1.0, 0.0], [0.0, 1.0]], dtype=torch.complex64, device=t.device)
E = torch.tensor(0.1)
mu = torch.tensor(0.2)
temperature = torch.tensor(1e-6)
particle_type = 'e'

# Time the function execution
start_time = time()

# Call lead_decimation to calculate Green's functions
gLr, gLa, gLless, gLmore = lead_decimation(E, t, epsilon0, mu, temperature, particle_type)
elapsed_time = time() - start_time
# Display results
print('Retarded Greens function:')
print(gLr)

print('Advanced Greens function:')
print(gLa)

print('Lesser Greens function:')
print(gLless)

print('Greater Greens function:')
print(gLmore)

print(f'Elapsed time: {elapsed_time:.4f} seconds')

Retarded Greens function:
tensor([[-0.0011-0.0500j,  0.0000-0.0000j],
        [ 0.0000-0.0000j, -0.0011-0.0500j]])
Advanced Greens function:
tensor([[-0.0011+0.0500j,  0.0000+0.0000j],
        [ 0.0000+0.0000j, -0.0011+0.0500j]])
Lesser Greens function:
tensor([[0.+0.0999j, 0.+0.0000j],
        [0.+0.0000j, 0.+0.0999j]])
Greater Greens function:
tensor([[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]])
Elapsed time: 0.0365 seconds
